#!/bin/sh

tmux start-server
tmux new-session -d -s sample -n vim
tmux send-keys -t sample:1 'rvm use 1.9.2@rails3' C-m
tmux send-keys -t sample:1 'vim' C-m

tmux new-window -t sample -n shell
tmux send-keys -t sample:2 'rvm use 1.9.2@rails3' C-m

tmux new-window -t sample -n spork
tmux send-keys -t sample:3 'rvm use 1.9.2@rails3' C-m
tmux send-keys -t sample:3 'spork' C-m

tmux new-window -t sample -n autotest
tmux send-keys -t sample:4 'rvm use 1.9.2@rails3' C-m
tmux send-keys -t sample:4 'sleep 10 && autotest' C-m

tmux new-window -t sample -n server
tmux send-keys -t sample:5 'rvm use 1.9.2@rails3' C-m
tmux send-keys -t sample:5 'rails s' C-m

tmux select-window -t sample:1
tmux attach-session -d -t sample
