#!/bin/sh
title=$(basename `pwd`)

issues

tmux start-server
tmux new-session -d -s $title -n zsh

tmux new-window -t $title -n console
tmux send-keys -t $title:2 'rails c' C-m

tmux new-window -t $title -n guard
tmux send-keys -t $title:3 'guard' C-m

tmux select-window -t $title:1
tmux attach-session -d -t $title
