eval "$(/opt/homebrew/bin/brew shellenv)"

# Add homebrew binaries
export PATH="/usr/local/bin:$PATH"

# Add my custom commands
export PATH="$HOME/bin:$PATH"

export PATH="$HOME/.npm-packages/bin:$PATH"

# Use postgres.app versions of pg utilites
export PATH=/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH
