# use vim as the visual editor
export VISUAL=vim
export EDITOR=$VISUAL

# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh
plugins=(rvm zsh-syntax-highlighting vagrant heroku brew gem gitfast)
export DISABLE_AUTO_UPDATE="true" # Don't let oh-my-zsh auto update
export ZSH_THEME="cjt" # Zsh theme, loaded from ~/.oh-my-zsh/themese. Set to 'random' for fun
source $ZSH/oh-my-zsh.sh

export BUNDLER_EDITOR='vim'

export HOMEBREW_CASK_OPTS="--appdir=/Applications"

[[ -r "$HOME/.auth" ]] && export `cat $HOME/.auth`

alias vim='mvim -v'
alias vi='mvim -v'

function conflicted { vim +Conflicted }

function capture { mutt -s 'Capture' chris+capture@ctoomey.com }

# Prevent correct of git slog
alias be='bundle exec'

## case-insensitive (all), partial-word and then substring completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' \
    'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# Show changed files in current branch, ignoring node_modules
function diff-without-node-modules() {
  if `git merge-base --is-ancestor master HEAD`; then
    git diff master..HEAD  --name-only | grep -v node_modules
  else
    echo 'Branch not rebased onto master' 1>&2
    return 1
  fi
}

# Serve the current directory. Pass in a port, or use default 8000
function simple-server {
  echo 'Simple-server URL coppied to the clipbaord'
  python -m SimpleHTTPServer 8123
  echo "http://simple-server.dev" | pbcopy
}

alias ql='qlmanage -p "$@" > /dev/null'

function trash() { mv $1 ~/.Trash }

function mkcd() { mkdir $1 && cd $1 }
function mkgit() { mkdir $1 && cd $1 && git init }
function mkclone() { git clone $1 && cd $( echo "$1" | sed -E 's|.*/(.*).git$|\1|' ) }

compdef g=git
function g {
  if [[ $# > 0 ]]; then
    if [ $1 = "." ]; then
      git status --short --branch .
    else
      git $@
    fi
  else
    git status --short --branch
  fi
}

function current_branch() {
    ref=$(git symbolic-ref HEAD 2> /dev/null) || return
    echo ${ref#refs/heads/}
}

function gitup {
    if git rev-parse --git-dir > /dev/null 2>&1; then
        cd "./"$(git rev-parse --show-cdup)
    else
        return
    fi
}

# Convenience aliases
alias ls="ls -FG"
alias l="ls -l"
alias la="ls -la"

alias ez='vim ~/.zshrc'
alias sz='source ~/.zshrc'

alias pgrep='pgrep -lf' # long output, match against full args list

# Load .env file into shell session for config vars
function envup {
  if [ -f .env ]; then
    export `cat .env`
  else
    return 1
  fi
}

# Allow [ or ] whereever you want
unsetopt nomatch

# Do not autoupdate tmux window titles
export DISABLE_AUTO_TITLE="true"

# Tmux aliases
alias tls="tmux list-sessions"
function tk {
  current_session=$(tmux display-message -p '#S')
  tmux switch-client -n
  tmux kill-session -t "$current_session"
}
function ta {
    if [ -z "$1" ]; then
        tmux attach
    else
        tmux attach-session -t $1
    fi
}
function tn {
  if [ -z "$1" ]; then
      session_name=$(basename `pwd`)
  else
      session_name=$1
  fi
  tmux new-session -d -s $session_name -n vim
  if [ -f zeus.json ]; then
    tmux new-window -t $session_name -n zeus 'zeus start' C-m
    # tmux split-window -t lplive:2.0 -h 'be foreman start web' C-m
    # tmux select-window -t $session_name:1
  fi
  tmux attach-session -t $session_name
}

for zsh_source in $HOME/.zsh/config/*.zsh; do
  source $zsh_source
done

# Edit the current line in $EDITOR
autoload -U edit-command-line
zle -N edit-command-line
bindkey '^x^e' edit-command-line

# Don't attempt spelling autocorrect
unsetopt correct_all

# Customize to your needs...
export PATH=$HOME/local/bin:$PATH:$HOME/bin:/usr/local/mysql/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/usr/X11/bin

# use .localrc for settings specific to one system
[[ -f ~/.localrc ]] && . ~/.localrc

[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
